#Still depends on triggering default gh deploy actions 
name: 'Zola Deploy to Pages'
description: 'Build and push a Zola site to GitHub Pages '
author: 'Shaleen Jain & Kenzi Connor'
branding:
  icon: 'zap'  
  color: 'green'
inputs:
  stage:
    description: 'How far to take the deploy.'
    required: false
    default: 'push'
    type: choice
    options:
      - dryrun
      - check
      - build
      - push
  target-repository:
    description: Repository to push the html to
    required: false
    default: ${{github.repository}}
    type: string
  target-branch:
    description: Branch to push to
    required: false
    default: gh-pages
    type: string
  skip-check:
    description: Skip checking external links
    required: false
    default: false
    type: boolean
  check-flags:
    description: Flags for just zola check (it fails on some build flags)
    required: false
    default: ''
    type: string
  build-dir:
    description: Directory to run zola build in - root of the content site
    required: false
    default: '.'
    type: string
  build-flags:
    description: flags for check and build, eg --drafts --base-url
    required: false
    default: ''
    type: string
  clear-history:
    description: DANGER- push -f an orphan to empty history of target
    required: false
    default: false
    type: boolean
  submodules:
    description: Checkout submodules (for themes)
    required: false
    default: true
    type: boolean
runs:
  using: 'composite'
  steps:
    - name: Output variables
      shell: bash
      run:  echo '${{ toJSON(inputs) }}'
    - name: Install zola
      uses: taiki-e/install-action@zola
    - name: Checkout source repo
      if: inputs.stage != 'dryrun'
      uses: actions/checkout@v4
      with:
        path: content
        submodules: ${{inputs.submodules}}
    - name: Zola check
      if: inputs.stage != 'dryrun' && !inputs.skip-check
      uses: ./actions/zola
      with:
        command: check
        content: ${{inputs.build-dir}}
        flags: ${{inputs.check-flags}}
    - name: Zola build
      if: inputs.stage == 'build' || inputs.stage == 'push'
      uses: ./actions/zola
      with:
        command: build
        content: ${{inputs.build-dir}}
        flags: ${{inputs.build-flags}}
        output: "output"
    - name: Push content
      if: inputs.stage == 'push'
      uses: ./actions/git-push
      with:
        repo: ${{inputs.target-repository}}
        branch: ${{inputs.target-branch}}
        path: "output"
        clear-history: ${{inputs.clear-history}}