#Still depends on triggering default gh deploy actions 
name: 'Zola Build & Push to Pages'
description: 'Build and push a Zola site to GitHub Pages '
author: 'Shaleen Jain'
branding:
  icon: 'zap'  
  color: 'green'
jobs:
  build:
    uses: ./.github/workflows/build.yml